"""Unofficial OneLake-inspired splash sprite.

Renders a chafa-generated ASCII-art OneLake logo with per-character 24-bit
colour, converted to Rich markup at import time.

Regenerate with:
    rsvg-convert -w 1000 docs/branding/onelake.svg -o /tmp/onelake-hires.png
    uv run --with Pillow python3 -c "
    from PIL import Image
    img = Image.open('/tmp/onelake-hires.png').convert('RGBA')
    pad = int(max(img.width, img.height) * 0.025)
    bg = Image.new('RGBA', (img.width+2*pad, img.height+2*pad), (255,255,255,255))
    bg.paste(img, (pad,pad), img)
    bg.convert('RGB').save('/tmp/onelake-final.png')
    "
    chafa --fg-only -c full -f symbols --symbols ascii --bg=black --size=40x40 /tmp/onelake-final.png
"""

from __future__ import annotations

import re
from importlib.metadata import PackageNotFoundError, version

from textual.widgets import Static

# ── Raw ANSI art generated by chafa from docs/branding/onelake.svg ───────
# Source: 1000×1000 rasterised SVG, alpha flattened onto white, 2.5% padding.
# chafa --fg-only -c full -f symbols --symbols ascii --bg=black --size=40x40
# Cursor-control sequences stripped; only SGR colour codes remain.
_SPRITE_ANSI_LINES = [
    "\x1b[39m\x1b[38;2;254;254;254m@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\x1b[39m",
    "\x1b[38;2;254;254;254m@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\x1b[39m",
    "\x1b[38;2;254;254;254m@@@@@@@@@@@@@@@\x1b[38;2;251;253;253m@\x1b[38;2;227;233;237mP\x1b[38;2;168;182;197mT\x1b[38;2;173;181;193m~\x1b[38;2;196;200;206m`\x1b[38;2;205;208;215m`\x1b[38;2;58;101;144mZ\x1b[38;2;80;123;163m@\x1b[38;2;178;196;214m@\x1b[38;2;254;254;254m@@@@@@@@@@@@@@@@\x1b[39m",
    "\x1b[38;2;254;254;254m@@@@@@@@@@@@@\x1b[38;2;224;244;252m@\x1b[38;2;108;213;246m@\x1b[38;2;56;145;185m~   \x1b[38;2;7;66;121mg\x1b[38;2;6;69;125m@\x1b[38;2;6;73;132m@\x1b[38;2;5;76;138m@\x1b[38;2;5;80;145m@\x1b[38;2;33;102;162m@\x1b[38;2;224;232;241m@\x1b[38;2;254;254;254m@@@@@@@@@@@@@@\x1b[39m",
    "\x1b[38;2;254;254;254m@@@@@@@@@@@\x1b[38;2;232;242;248m@\x1b[38;2;102;205;244m@\x1b[38;2;41;192;242m@\x1b[38;2;37;162;206m$\x1b[38;2;11;81;145my\x1b[38;2;9;96;169my\x1b[38;2;7;106;188mg\x1b[38;2;4;105;187m@\x1b[38;2;1;115;204m@\x1b[38;2;0;119;209m@\x1b[38;2;0;123;212m@\x1b[38;2;0;127;213m@\x1b[38;2;0;131;215m@\x1b[38;2;0;134;216m@\x1b[38;2;17;138;212m@\x1b[38;2;87;176;229m@\x1b[38;2;153;208;239m@\x1b[38;2;244;247;251m@\x1b[38;2;254;254;254m@@@@@@@@@@@\x1b[39m",
    "\x1b[38;2;254;254;254m@@@@@@@\x1b[38;2;246;247;249m@\x1b[38;2;141;173;201m@\x1b[38;2;51;113;168m@\x1b[38;2;9;115;183m@\x1b[38;2;28;178;237m@\x1b[38;2;35;186;240m@\x1b[38;2;43;194;242m@\x1b[38;2;37;161;214m@\x1b[38;2;15;94;166m@\x1b[38;2;12;98;173m@\x1b[38;2;10;102;179m@\x1b[38;2;8;105;186m@\x1b[38;2;5;109;192m@\x1b[38;2;3;112;199m@\x1b[38;2;1;115;205m@\x1b[38;2;0;119;209m@\x1b[38;2;0;122;212m@\x1b[38;2;0;126;213m@\x1b[38;2;0;129;214m@\x1b[38;2;0;132;215m@\x1b[38;2;0;134;216m@\x1b[38;2;0;137;217m@\x1b[38;2;28;148;220m@\x1b[38;2;133;197;236m@\x1b[38;2;253;253;253m@\x1b[38;2;254;254;254m@@@@@@@@\x1b[39m",
    "\x1b[38;2;254;254;254m@@@@@@\x1b[38;2;137;165;190m@\x1b[38;2;6;72;130m@\x1b[38;2;5;76;139m@\x1b[38;2;8;109;176m@\x1b[38;2;19;170;235m@\x1b[38;2;27;177;237m@\x1b[38;2;34;185;240m@\x1b[38;2;42;193;242m@\x1b[38;2;48;196;241m@\x1b[38;2;19;88;155m@\x1b[38;2;16;92;161m@\x1b[38;2;14;95;168m@\x1b[38;2;12;99;174m@\x1b[38;2;10;102;180m@\x1b[38;2;8;105;186m@\x1b[38;2;6;108;192m@\x1b[38;2;4;111;197m@\x1b[38;2;2;114;202m@\x1b[38;2;0;117;207m@\x1b[38;2;0;120;210m@\x1b[38;2;0;122;212m@\x1b[38;2;0;125;212m@\x1b[38;2;0;127;213m@\x1b[38;2;0;128;214m@\x1b[38;2;0;130;214m@\x1b[38;2;0;131;215m@\x1b[38;2;132;192;234m@\x1b[38;2;254;254;254m@@@@@@@\x1b[39m",
    "\x1b[38;2;254;254;254m@@@@@\x1b[38;2;193;203;215mF\x1b[38;2;7;65;119m4\x1b[38;2;6;69;126m@\x1b[38;2;5;79;141m@\x1b[38;2;9;158;231m@\x1b[38;2;16;166;234m@\x1b[38;2;23;174;236m@\x1b[38;2;31;182;239m@\x1b[38;2;38;189;241m@\x1b[38;2;46;197;243m@\x1b[38;2;39;152;203m@\x1b[38;2;21;85;150m@\x1b[38;2;18;89;156m@\x1b[38;2;16;92;162m@\x1b[38;2;14;95;167m@\x1b[38;2;12;98;173m@\x1b[38;2;10;101;178m@\x1b[38;2;9;104;183m@\x1b[38;2;7;107;188m@\x1b[38;2;5;109;193m@\x1b[38;2;4;111;197m@\x1b[38;2;2;113;201m@\x1b[38;2;1;115;204m@\x1b[38;2;0;117;207m@\x1b[38;2;0;119;209m@\x1b[38;2;0;120;210m@\x1b[38;2;0;121;211m@@\x1b[38;2;61;151;221m@\x1b[38;2;253;253;254m@\x1b[38;2;254;254;254m@@@@@\x1b[39m",
    "\x1b[38;2;254;254;254m@@@@\x1b[38;2;240;242;245m@  \x1b[38;2;7;67;122m@\x1b[38;2;2;116;187m@\x1b[38;2;4;154;230m@\x1b[38;2;12;161;233m@\x1b[38;2;19;169;235m@\x1b[38;2;26;176;237m@\x1b[38;2;33;184;239m@\x1b[38;2;41;192;241m@\x1b[38;2;48;199;244m@\x1b[38;2;35;126;179m@\x1b[38;2;23;82;143m@\x1b[38;2;21;85;149m@\x1b[38;2;19;88;154m@\x1b[38;2;17;91;159m@\x1b[38;2;15;94;165m@\x1b[38;2;14;96;169m@\x1b[38;2;12;99;174m@\x1b[38;2;10;101;178m@\x1b[38;2;9;103;182m@\x1b[38;2;8;105;186m@\x1b[38;2;6;107;189m@\x1b[38;2;5;109;192m@\x1b[38;2;5;110;194m@\x1b[38;2;4;111;197m@\x1b[38;2;3;112;198m@\x1b[38;2;3;113;199m@\x1b[38;2;3;113;200m@\x1b[38;2;75;150;213m@\x1b[38;2;254;254;254m@@@@@\x1b[39m",
    "\x1b[38;2;254;254;254m@@@@\x1b[38;2;192;231;242m@  \x1b[38;2;7;66;120m4\x1b[38;2;0;144;223m$\x1b[38;2;0;148;229m@\x1b[38;2;6;155;231m@\x1b[38;2;12;162;233m@\x1b[38;2;19;170;235m@\x1b[38;2;26;177;237m@\x1b[38;2;33;184;239m@\x1b[38;2;40;191;241m@\x1b[38;2;47;198;243m@\x1b[38;2;35;127;179m@\x1b[38;2;24;79;138m@\x1b[38;2;24;80;141m@\x1b[38;2;22;83;146m@\x1b[38;2;20;86;150m@\x1b[38;2;19;88;155m@\x1b[38;2;17;91;159m@\x1b[38;2;16;93;164m@\x1b[38;2;14;95;167m@\x1b[38;2;13;97;171m@\x1b[38;2;12;99;174m@\x1b[38;2;11;100;177m@\x1b[38;2;10;102;179m@\x1b[38;2;9;103;181m@\x1b[38;2;9;104;183m@\x1b[38;2;8;104;184m@\x1b[38;2;8;105;184m@\x1b[38;2;8;105;185m@\x1b[38;2;203;222;238m@\x1b[38;2;254;254;254m@@@@\x1b[39m",
    "\x1b[38;2;254;254;254m@@@@\x1b[38;2;199;243;252m@\x1b[38;2;67;168;200my  \x1b[38;2;0;141;219m@\x1b[38;2;0;148;229m@@\x1b[38;2;5;154;230m@\x1b[38;2;11;161;233m@\x1b[38;2;18;168;235m@\x1b[38;2;24;175;237m@\x1b[38;2;31;182;239m@\x1b[38;2;38;189;241m@\x1b[38;2;44;195;242m@\x1b[38;2;38;148;199m@\x1b[38;2;25;79;138m@@\x1b[38;2;24;79;138m@\x1b[38;2;24;80;141m@\x1b[38;2;22;83;145m@\x1b[38;2;21;85;149m@\x1b[38;2;20;87;152m@\x1b[38;2;18;89;156m@\x1b[38;2;62;130;183m$\x1b[38;2;80;148;196m@\x1b[38;2;89;158;203m@\x1b[38;2;78;152;201m@\x1b[38;2;59;136;191m@\x1b[38;2;21;101;171m$\x1b[38;2;14;96;169m@\x1b[38;2;13;96;170m@\x1b[38;2;144;180;214m@\x1b[38;2;254;254;254m@@@@\x1b[39m",
    "\x1b[38;2;254;254;254m@@@@\x1b[38;2;241;251;253m@\x1b[38;2;100;224;250m@\x1b[38;2;74;169;201mg \x1b[38;2;2;125;198m$\x1b[38;2;0;146;226m@\x1b[38;2;0;147;228m@\x1b[38;2;0;148;229m@\x1b[38;2;3;152;230m@\x1b[38;2;9;158;232m@\x1b[38;2;15;165;234m@\x1b[38;2;21;171;236m@\x1b[38;2;27;178;237m@\x1b[38;2;33;184;239m@\x1b[38;2;38;189;241m@\x1b[38;2;40;180;229m@\x1b[38;2;28;102;158m@\x1b[38;2;25;79;138m@@@\x1b[38;2;50;103;154m$\x1b[38;2;137;193;218m@\x1b[38;2;188;244;254m@@@\x1b[38;2;187;244;254m@\x1b[38;2;185;243;254m@\x1b[38;2;180;242;254m@\x1b[38;2;174;240;253m@\x1b[38;2;141;210;234m@\x1b[38;2;46;116;173m@\x1b[38;2;163;189;215m@\x1b[38;2;254;254;254m@@@@\x1b[39m",
    "\x1b[38;2;254;254;254m@@@@@\x1b[38;2;162;235;252m@\x1b[38;2;109;226;251m@\x1b[38;2;105;210;236m@\x1b[38;2;54;146;190m@\x1b[38;2;0;136;210m@\x1b[38;2;0;140;216m@\x1b[38;2;0;143;221m@\x1b[38;2;0;145;224m@\x1b[38;2;0;147;226m@\x1b[38;2;5;152;228m@\x1b[38;2;10;158;230m@\x1b[38;2;16;163;230m@\x1b[38;2;21;167;230m@\x1b[38;2;25;169;228m@\x1b[38;2;29;170;224m@\x1b[38;2;32;170;219m@\x1b[38;2;31;146;194m@\x1b[38;2;65;124;170m@\x1b[38;2;145;200;222m@\x1b[38;2;188;244;254m@@@@@@\x1b[38;2;185;243;254m@\x1b[38;2;180;242;254m@\x1b[38;2;174;240;253m@\x1b[38;2;168;239;253m@\x1b[38;2;162;238;252m@\x1b[38;2;242;245;248m@\x1b[38;2;254;254;254m@@@@\x1b[39m",
    "\x1b[38;2;254;254;254m@@@@@@\x1b[38;2;140;232;251m@\x1b[38;2;113;227;251m@\x1b[38;2;119;228;251m@\x1b[38;2;125;229;251m@\x1b[38;2;100;207;240m@\x1b[38;2;69;182;228m@\x1b[38;2;46;165;221m@\x1b[38;2;24;148;213m@\x1b[38;2;0;135;208m@@\x1b[38;2;4;138;208m@\x1b[38;2;16;144;208m@\x1b[38;2;43;161;213m@\x1b[38;2;70;176;219m@\x1b[38;2;125;207;234m@\x1b[38;2;180;239;251m@\x1b[38;2;187;243;254m@\x1b[38;2;187;244;254m@@\x1b[38;2;187;243;254m@\x1b[38;2;186;243;254m@\x1b[38;2;185;243;254m@\x1b[38;2;183;243;254m@\x1b[38;2;179;242;253m@\x1b[38;2;174;241;253m@\x1b[38;2;169;239;253m@\x1b[38;2;164;238;253m@\x1b[38;2;159;237;253m@\x1b[38;2;216;246;252m@\x1b[38;2;254;254;254m@@@@@\x1b[39m",
    "\x1b[38;2;254;254;254m@@@@@@@\x1b[38;2;175;238;252m@\x1b[38;2;113;227;251m@\x1b[38;2;118;228;251m@\x1b[38;2;123;229;251m@\x1b[38;2;129;230;251m@\x1b[38;2;133;231;252m@\x1b[38;2;138;233;252m@\x1b[38;2;143;234;252m@\x1b[38;2;148;235;252m@\x1b[38;2;152;235;252m@\x1b[38;2;156;236;253m@\x1b[38;2;160;237;253m@\x1b[38;2;163;238;253m@\x1b[38;2;166;239;253m@\x1b[38;2;168;239;253m@\x1b[38;2;169;240;253m@\x1b[38;2;170;240;253m@@\x1b[38;2;169;240;253m@\x1b[38;2;168;239;253m@\x1b[38;2;166;239;253m@\x1b[38;2;164;238;253m@\x1b[38;2;160;238;253m@\x1b[38;2;157;237;253m@\x1b[38;2;153;236;252m@\x1b[38;2;150;235;252m@\x1b[38;2;217;246;252m@\x1b[38;2;254;254;254m@@@@@@\x1b[39m",
    "\x1b[38;2;254;254;254m@@@@@@@@\x1b[38;2;228;248;253m@\x1b[38;2;140;231;251m@\x1b[38;2;112;227;251m@\x1b[38;2;116;228;251m@\x1b[38;2;121;228;251m@\x1b[38;2;125;229;251m@\x1b[38;2;129;230;251m@\x1b[38;2;132;231;252m@\x1b[38;2;135;232;252m@\x1b[38;2;139;233;252m@\x1b[38;2;141;233;252m@\x1b[38;2;144;234;252m@\x1b[38;2;145;234;252m@\x1b[38;2;147;234;252m@\x1b[38;2;148;235;252m@@@\x1b[38;2;147;235;252m@\x1b[38;2;146;234;252m@\x1b[38;2;145;234;252m@\x1b[38;2;143;234;252m@\x1b[38;2;140;233;252m@\x1b[38;2;137;232;252m@\x1b[38;2;184;240;252m@\x1b[38;2;246;252;253m@\x1b[38;2;254;254;254m@@@@@@@\x1b[39m",
    "\x1b[38;2;254;254;254m@@@@@@@@@@\x1b[38;2;236;250;253m@\x1b[38;2;173;238;252m@\x1b[38;2;112;226;251m@\x1b[38;2;108;226;251m@\x1b[38;2;111;227;251m@\x1b[38;2;114;227;251m@\x1b[38;2;117;228;251m@\x1b[38;2;119;228;251m@\x1b[38;2;121;229;251m@\x1b[38;2;123;229;251m@\x1b[38;2;124;229;251m@\x1b[38;2;125;230;251m@\x1b[38;2;126;230;251m@@@\x1b[38;2;125;230;251m@\x1b[38;2;124;229;251m@\x1b[38;2;123;229;251m@\x1b[38;2;143;233;251m@\x1b[38;2;198;243;252m@\x1b[38;2;250;252;253m@\x1b[38;2;254;254;254m@@@@@@@@@\x1b[39m",
    "\x1b[38;2;254;254;254m@@@@@@@@@@@@@\x1b[38;2;249;252;253m@\x1b[38;2;213;245;252m@\x1b[38;2;173;238;252m@\x1b[38;2;150;233;251m@\x1b[38;2;126;228;251m@\x1b[38;2;103;224;250m@\x1b[38;2;102;224;250m@\x1b[38;2;103;225;250m@\x1b[38;2;104;225;250m@\x1b[38;2;114;226;250m@\x1b[38;2;138;231;251m@\x1b[38;2;157;235;252m@\x1b[38;2;186;240;252m@\x1b[38;2;219;247;253m@\x1b[38;2;253;253;254m@\x1b[38;2;254;254;254m@@@@@@@@@@@@\x1b[39m",
    "\x1b[38;2;254;254;254m@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\x1b[39m",
    "\x1b[38;2;254;254;254m@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\x1b[39m",
]

# ── Convert ANSI escape sequences to Rich markup once at import ──────────

_SGR_RE = re.compile(r"\x1b\[([0-9;]+)m")


def _ansi_line_to_rich(line: str) -> str:
    """Convert a single line of ANSI SGR sequences to Rich markup.

    ``re.split`` with a capturing group alternates between visible text
    (even indices) and captured SGR parameter strings (odd indices).
    We track position to avoid misclassifying visible chars like ``4``
    as SGR codes.
    """
    parts: list[str] = []
    color_open = False
    for i, segment in enumerate(_SGR_RE.split(line)):
        if not segment:
            continue
        if i % 2 == 0:
            # Visible text between ANSI sequences
            parts.append(segment)
        else:
            # Captured SGR parameter string
            if segment == "39":
                if color_open:
                    parts.append("[/]")
                    color_open = False
            elif segment.startswith("38;2;"):
                if color_open:
                    parts.append("[/]")
                _, _, r, g, b = segment.split(";")
                parts.append(f"[rgb({r},{g},{b})]")
                color_open = True
    if color_open:
        parts.append("[/]")
    return "".join(parts)


_SPRITE_MARKUP = "\n".join(_ansi_line_to_rich(ln) for ln in _SPRITE_ANSI_LINES)
_SPRITE_LINES = _SPRITE_MARKUP.split("\n")

# ── Figlet "ansi_shadow" wordmark (pre-generated, no runtime dep) ────
# Generated via: pyfiglet.figlet_format("ONELAKE", font="ansi_shadow")

_WORDMARK_LINES = [
    " ██████╗ ███╗   ██╗███████╗██╗      █████╗ ██╗  ██╗███████╗",
    "██╔═══██╗████╗  ██║██╔════╝██║     ██╔══██╗██║ ██╔╝██╔════╝",
    "██║   ██║██╔██╗ ██║█████╗  ██║     ███████║█████╔╝ █████╗  ",
    "██║   ██║██║╚██╗██║██╔══╝  ██║     ██╔══██║██╔═██╗ ██╔══╝  ",
    "╚██████╔╝██║ ╚████║███████╗███████╗██║  ██║██║  ██╗███████╗",
    " ╚═════╝ ╚═╝  ╚═══╝╚══════╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝",
]

try:
    _APP_VERSION = version("onelake-tui")
except PackageNotFoundError:
    _APP_VERSION = "dev"

_WORDMARK_WIDTH = max(len(ln) for ln in _WORDMARK_LINES)
_SHIMMER_COLOR = "#E8F4FD"
_SHIMMER_BAND = 8


def _render_wordmark(color: str, shimmer_col: int | None = None) -> list[str]:
    """Render the figlet wordmark as Rich-markup lines with optional shimmer."""
    if shimmer_col is None:
        return [f"[bold {color}]{ln}[/]" for ln in _WORDMARK_LINES]

    result: list[str] = []
    for ln in _WORDMARK_LINES:
        parts: list[str] = []
        run_color: str | None = None
        run_chars: list[str] = []
        for i, ch in enumerate(ln):
            if ch == " ":
                if run_chars:
                    parts.append(f"[bold {run_color}]{''.join(run_chars)}[/]")
                    run_chars.clear()
                    run_color = None
                parts.append(" ")
            else:
                c = _SHIMMER_COLOR if shimmer_col <= i < shimmer_col + _SHIMMER_BAND else color
                if c == run_color:
                    run_chars.append(ch)
                else:
                    if run_chars:
                        parts.append(f"[bold {run_color}]{''.join(run_chars)}[/]")
                    run_color = c
                    run_chars = [ch]
        if run_chars:
            parts.append(f"[bold {run_color}]{''.join(run_chars)}[/]")
        result.append("".join(parts))
    return result


# ── Public API ───────────────────────────────────────────────────────────

from rich.console import Group  # noqa: E402
from rich.table import Table  # noqa: E402
from rich.text import Text  # noqa: E402

RenderableType = object  # duck-typed; anything Rich can render


def render_sprite() -> str:
    """Return the sprite as Rich markup."""
    return _SPRITE_MARKUP


def get_welcome() -> RenderableType:
    """Full static welcome panel (sprite + figlet wordmark + hints)."""
    return _build_welcome()


def _build_welcome(shimmer_col: int | None = None) -> RenderableType:
    """Build the side-by-side welcome panel.

    Left column : chafa sprite
    Right column: figlet wordmark (with optional shimmer), badge,
                  tagline, and version.
    Below       : keyboard-shortcut hints.
    """
    num_rows = len(_SPRITE_LINES)

    wordmark = _render_wordmark("#0078D4", shimmer_col)

    # Right-column content, vertically centred against the sprite.
    right: list[str] = [""] * num_rows
    start = max(0, (num_rows - 15) // 2)
    for i, ln in enumerate(wordmark):
        right[start + i] = ln
    # 1-row gap, then badge
    right[start + 7] = "[bold #FFB900]UNOFFICIAL TUI[/]"
    # 1-row gap, then metadata
    right[start + 9] = "[dim]Community-built terminal UI[/]"
    right[start + 10] = "[dim]for Microsoft Fabric OneLake[/]"
    right[start + 11] = "[dim]Not affiliated with Microsoft[/]"
    right[start + 12] = f"[dim]v{_APP_VERSION}[/]"

    tbl = Table(
        show_header=False,
        show_edge=False,
        show_lines=False,
        pad_edge=False,
        box=None,
        padding=(0, 3, 0, 0),
    )
    tbl.add_column(no_wrap=True)
    tbl.add_column(no_wrap=True)
    for i in range(num_rows):
        tbl.add_row(_SPRITE_LINES[i], right[i])

    hints = Text.from_markup(
        "\n  [dim]↑↓ or j/k Navigate  │  Enter Expand  │  / Search[/]"
        "\n  [dim]Tab/h/l Panels  │  g/G Top/Bottom  │  y Copy menu  │  ? Help[/]\n"
    )

    return Group(tbl, hints)


class OneLakeSprite(Static):
    """Unofficial OneLake-inspired splash art with shimmer animation."""

    DEFAULT_CSS = """
    OneLakeSprite {
        width: auto;
        height: auto;
    }
    """

    _START = -_SHIMMER_BAND - 2
    _END = _WORDMARK_WIDTH + 2

    def __init__(self, **kwargs) -> None:
        super().__init__(_build_welcome(), **kwargs)
        self._frame = self._START

    def on_mount(self) -> None:
        total = self._END - self._START
        self.set_interval(0.06, self._tick, repeat=total)

    def _tick(self) -> None:
        self._frame += 1
        col = self._frame if 0 <= self._frame < _WORDMARK_WIDTH else None
        self.update(_build_welcome(shimmer_col=col))
